version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    container_name: ailembrei_pg
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/data/postgres
